# Generated by Django 4.1.13 on 2024-11-24 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abonne',
            name='historique_emprunts',
        ),
        migrations.RemoveField(
            model_name='abonne',
            name='liste_emprunts',
        ),
    ]
